version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/springmysql-deploy/

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: /deploy_scripts/prepare_deploy.sh
      timeout: 60
      runas: root 

  AfterInstall:
    - location: /deploy_scripts/run_deploy.sh
      timeout: 60
      runas: root