version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Noting to do in the pre build phase ...
      - REGION=ap-northeast-2
      - REPOSITORY_URI=520666629845.dkr.ecr.ap-northeast-2.amazonaws.com
      - IMAGE_TAG=0.1.1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - BUILD_TAG=${COMMIT_HASH:=0.1.1}
      - CONTAINER_NAME=springmysql
      - echo Logging in to Amazon ECR...
      - aws --version
      # - aws ecr get-login-password --region $REGION | docker login -u AWS --password-stdin $REPOSITORY_URI
      - aws ecr get-login-password --region 'ap-northeast-2' | docker login --username AWS --password-stdin 520666629845.dkr.ecr.ap-northeast-2.amazonaws.com/springmysql
      
    
  build:
    commands:
      - echo starting build stage
      - mvn package
      - mvn install
      - docker tag $REPOSITORY_URI/$IMAGE_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_NAME:$BUILD_TAG


  post_build:
    commands:
      - pwd
      - echo build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$IMAGE_NAME:$IMAGE_TAG
      - docker push $REPOSITORY_URI/$IMAGE_NAME:$BUILD_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI/$IMAGE_NAME:$BUILD_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  type: zip
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
 
cache:
  paths:
    - '/root/.m2/**/*'