apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springmysql-pvc
  namespace: homeeee
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc
  volumeMode: Filesystem