version: '3'
services:
  spring-app:
    image: taeeyoul/springmysql:1.0.0
    # image: 864563395693.dkr.ecr.ap-northeast-2.amazonaws.com/springmysql:1.1.7
    container_name: springmysql
    environment:
      # spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      # spring.datasource.url=jdbc:mysql://aurora-instance-skcc-07456-p-an2-0.cgxth7zggvw1.ap-northeast-2.rds.amazonaws.com:3306/tutorial?serverTimezone=UTC&characterEncoding=UTF-8
      # spring.datasource.driver-class-name=software.aws.rds.jdbc.mysql.Driver
      # spring.datasource.url=jdbc:mysql:aws://rds-skcc-07456-p-aurora-mysql.cluster-cgxth7zggvw1.ap-northeast-2.rds.amazonaws.com:3306/tutorial?serverTimezone=UTC&characterEncoding=UTF-8
      # spring.datasource.username=tutorial
      # spring.datasource.password=tutorial
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      # - DB_CONNECTION=jdbc:mysql://localhost:3306/tutorial?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - DB_CONNECTION=jdbc:mysql://mysql:3306/tutorial?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - DB_USERNAME=tutorial
      - DB_PASSWORD=tutorial
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=tutorial
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=tutorial
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # - ./initdb.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      # - ./db/conf.d/my.cnf:/etc/mysql/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d

