# Alpine Linux를 기반으로 하는 이미지를 선택합니다.
FROM alpine

# 필요한 패키지 설치 및 업데이트
RUN apk update && \
    apk add --no-cache python3 sqlite git && \
    python3 -m ensurepip && \
    pip3 install --no-cache-dir --upgrade pip setuptools

# 작업 디렉토리를 생성합니다.
WORKDIR /app

# git clone을 수행하고 작업 디렉토리로 이동합니다.
ENV GIT_URL="https://github.com/SEOTAEEYOUL/item.git"
RUN git clone $GIT_URL /app && \
    cd /app

# Python 스크립트 실행
CMD ["python3", "load_data.py"]
