def label = "springmysql-${UUID.randomUUID().toString()}"

pipeline {
    agent any
    

        
    stages {
        stage('github-clone') {
            // Get some code from a GitHub repository
            steps {
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/SEOTAEEYOUL/SpringBootMySQL'
            }
        }
        // stage("checkout"){
        //     steps{
        //         checkout scm
        //     }
        // }
        stage('Build') {
            steps {
                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean package"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            // post {
            //     // If Maven was able to run the tests, even if some of the test
            //     // failed, record the test results and archive the jar file.
            //     success {
            //         junit '**/target/surefire-reports/TEST-*.xml'
            //         archiveArtifacts 'target/*.jar'
            //     }
            // }
        }

        stage("Delete container and image"){
            steps{
                sh "docker rm -f springmysql "
                sh "docker rmi springmysql" 
            }
        }
        stage("image build"){
            steps{
                script {
                    myapp = docker.build("springmysql:1.0.0")
                }
            }
        }
        // stage("push image"){
        //     steps{
        //         script{
        //             docker.withRegistry('https://myregistry.com','registry-auth'){
        //                 myapp.push("latest")
        //             }
        //         }
        //     }
        // }
        stage("deploy springmysql"){
            steps{
                sh "docker run --name webserver --net demonet -d --name -p 18080:8080 springmysql"
            }
        }
    }
}

// pipeline{
//     agent any
//     stages{
//         stage("checkout"){
//             steps{
//                 checkout scm
//             }
//         }
//         stage("Delete container and image"){
//             steps{
//                 sh "docker rm -f webserver "
//                 sh "docker rmi myregistry.com/root/webtest/webserver" 
//             }
//         }
//         stage("image build"){
//             steps{
//                 script{
//                     myapp = docker.build("myregistry.com/root/webtest/webserver")
//                 }
//             }
//         }
//         stage("push image"){
//             steps{
//                 script{
//                     docker.withRegistry('https://myregistry.com','registry-auth'){
//                         myapp.push("latest")
//                     }
//                 }
//             }
//         }
//         stage("deploy Webserver"){
//             steps{
//                 sh "docker run --name webserver --net demonet -d --name -p 1888:80 myregistry.com/root/webtest/webserver"
//             }
//         }
//     }
// }